### ISSUE TITLE
mnl_socket_sendto(channel->nl, nlh, nlh->nlmsg_len) caused error of netlink attribute type 1 has an invalid length

### ISSUE THREAD

**Issue by nobody93** [bmegli/wifi-scan#26]
I had an error warning message of attribute type 1 has an invalid length every time calling get_family_and_scan_ids which called prepare_nl_message in message type GENL_ID_CTRL, then called send_nl_message at statement:

if (mnl_socket_sendto(channel->nl, nlh, nlh->nlmsg_len) < 0) {
}

I am running it on imx6 and kernel 4.19, what could be wrong there?

Thank you.

**Comment by bmegli** [comment]
Hi,

> I had

Do you still have it? This should be fixed in 240eac667e957d1c34758544ad38ea8dcbb48ac7 (yesterday), try the current master.

```C
mnl_socket_sendto(channel->nl, nlh, nlh->nlmsg_len)
```

This is the function that actually sends the netlink data to the kernel. This is why the problem manifests here. The real cause is malformed message (netlink attribute encoded with inccorect data type). 

> error warning message

Depending on kernel configuration this may end in [nothing, warning or error](https://github.com/torvalds/linux/blob/80f232121b69cc69a31ccb2b38c1665d770b0710/lib/nlattr.c#L178)

> every time calling get_family_and_scan_ids

Yes, this is what should happen. Typically this function is called only once during initialization.

> I am running it on imx6 and kernel 4.19

Your kernel configuration may be different, so you may experience error instead of warning if `NL_VALIDATE_STRICT_ATTRS` is set.

> what could be wrong there

This should be already fixed in the current master (yesterday).
If it is not, let me know and we may investigate further.

**Comment by nobody93** [comment]
Brilliant, you indeed fixed it. Thank you Bartosz.
