### ISSUE TITLE
Request for a function to show associations from AP side

### ISSUE THREAD

**Issue by nickbash11** [bmegli/wifi-scan#27]
I am looking for a solution to get a customizable list of associated stations like the view from 'iw dev wlan0 station dump' or 'iwinfo wlan0 assoc' on OpenWRT.

I am a new in C, so that attempts to understand the source code of iw library (how it gets the list of associated IBSS) makes my brain blowing up. Want to do [that script](https://github.com/nickbash11/mesh-blocker/blob/master/files/etc/mesh-blocker/blocker.sh) in C.

Is it possible in the future?

**Comment by bmegli** [comment]
> Is it possible in the future?

I currently have no plans to implement such feature.\
This is beyond the scope of this minimalistic library

Technically such extension is possible.

> I am a new in C, so that attempts to understand the source code of iw library (how it gets the list of associated IBSS) makes my brain blowing up. Want to do that script in C.

Doing this from C will be hard and time consuming (programmer's time). Rethink if you really need to do that from C (e.g. need to be rapidly called on thin embedded system).

wifi-scan was written for embedded system that was already reaching 90% CPU utilization and needed real-time wifi signal monitoring. Even retrospectively I am not sure it was worth the effort.

> I am looking for a solution to get a customizable list of associated stations like the view from 'iw dev wlan0 station dump' or 'iwinfo wlan0 assoc' on OpenWRT.

If you still want to do it in C here's a sketch how to hack wifi-scan for station dump. 

For station dump you would probably have to (links to iw code):
1. Send [station dump request](https://github.com/Distrotech/iw/blob/fe424b2465118eca166b2e901b5a378bf9582fb0/station.c#L503)
2. With [setup](https://github.com/Distrotech/iw/blob/fe424b2465118eca166b2e901b5a378bf9582fb0/station.c#L494) [handler](https://github.com/Distrotech/iw/blob/fe424b2465118eca166b2e901b5a378bf9582fb0/station.c#L94) for result

iw uses [libnl](https://www.infradead.org/~tgr/libnl/), wifi-scan uses [libmnl](https://www.netfilter.org/projects/libmnl/) (minimalistic netlink library). They are similiar, not identic.

Since [wifi-scan-station](https://github.com/bmegli/wifi-scan/blob/master/wifi_scan.c#L712) uses the same netlink [command](https://github.com/bmegli/wifi-scan/blob/master/wifi_scan.c#L740) NL80211_CMD_GET_STATION you could hack it:
- for requesting dump [here](https://github.com/bmegli/wifi-scan/blob/master/wifi_scan.c#L740) like iw makes [here](https://github.com/Distrotech/iw/blob/fe424b2465118eca166b2e901b5a378bf9582fb0/station.c#L503), probably removing excess attributes (BSSID, etc)
- and handle the result [here](https://github.com/bmegli/wifi-scan/blob/master/wifi_scan.c#L750) like iw does [here](https://github.com/Distrotech/iw/blob/fe424b2465118eca166b2e901b5a378bf9582fb0/station.c#L94)


If I were you, I would start by changing those few lines, adding some printfs (or following in debugger).
If you get this working you could turn it into separate functionality in wifi-scan (e.g. `wifi_scan_station_dump`)


I haven't looked into 'iwinfo wlan0 assoc' but you could also follow reference implementation.


Kind regards (and good luck)

**Comment by nickbash11** [comment]
Thank you! I've just wanted to rewrite it for mesh-routers based on OpenWRT. I think that the function "mac white list" must be work as a native.

For some reasons nl80211 maintainers have broken needed function.
